### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by rchannel** [sijis/err-salt#1]
How do I configure this to know where my salt-master is and the authentication for it?

**Comment by sijis** [comment]
@rchannel, sorry but I never saw this.
So, if you haven't figured it out by now, you have tell errbot to configure it with
!plugin config Salt
Or !config Salt (on older err versions)

**Comment by rchannel** [comment]
Is there a way to restrict this to certain users?

**Comment by sijis** [comment]
Typically the !plugin config is only for botadmins.

You can further restrict by using errbot built-in acl feature. Look for
ACCESS_CONTROLS in your config.py

**Comment by rchannel** [comment]
Thanks.
